name: food_delivery_app
description: A Flutter app with BLoC and food API integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^0.13.5
  equatable: ^2.0.5
  cached_network_image: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
   - lib/assest/1.png




